ifndef::imagesdir[:imagesdir: ../images]

[[section-introduction-and-goals]]
== Introduction and Goals
RTVE wants to offer a web application based on the famous Spanish TV show 
https://es.wikipedia.org/wiki/Saber_y_ganar["Saber y Ganar"] 
to its users in commemoration of the 28th anniversary of the show. This show consisted on 
answering a number of questions with different types and subjects obtaining a prize for 
each question well answered.

The expected goal is to offer a well-desgined game that maintains all the quality standards
that the company offers like maintainability, security, etc...; while trying to fulfill the
user's needs to provide a positive UX.   

[role="arc42help"]
****
Notes:
The shown requirements may increase if during the development
of the project more features are included. Please, refer to
https://github.com/Arquisoft/wiq_en3b/wiki/Lab-Assignment-Overview#optional-features[Optional features] for more info.
****

=== Requirements Overview

The web application must meet the following requirements:

[options="header",cols="1,2" ]
|===
| Requirement | Description  
| Accesibility | It must be taken care of the different HTML standards so Screen-readers users can also play the game. Also, take care of features like coloring.  
| Availability | The system must always be available so users can play at any time.
| User Registration and Login | Users must be able to register into game so its data is stored for later consult.
| WikiData | The questions and answer options must be generated using the WikiData API.
| Timer | All the questions must have a time to answer.
| APIs | The game must expose two APIs that retrieves information about 1. Users and 2. Questions generated. 
|===



[role="arc42help"]
****
.Contents
Short description of the functional requirements, driving forces, extract (or abstract)
of requirements. Link to (hopefully existing) requirements documents
(with version number and information where to find it).

.Motivation
From the point of view of the end users a system is created or modified to
improve support of a business activity and/or improve the quality.

.Form
Short textual description, probably in tabular use-case format.
If requirements documents exist this overview should refer to these documents.

Keep these excerpts as short as possible. Balance readability of this document with potential redundancy w.r.t to requirements documents.


.Further Information

See https://docs.arc42.org/section-1/[Introduction and Goals] in the arc42 documentation.

****

=== Quality Goals


=== Stakeholders

[options="header",cols="1,2a,2" ]
|===
|Role/Name|Contact|Expectations
| RTVE | rtve.dircom@rtve.es | A web application that emulates the functionality of the famous Spanish TV show "Saber y Ganar". 
| HappySw | contact_projects@happysw.es | An application that meets all the  requirements asked by RTVE mantaining the quality that offers the company. 
| Professors 
| 
* Pablo González: gonzalezgpablo@uniovi.es 
* Jose Labra: labra@uniovi.es
| A well-designed web application that fulfills the functional requirements for the game to work, as well as, the quality requirements.
| Users |  | A "Saber y Ganar" web game to test their knowdlege on different fields. The game must be easy to use and must record all of their past games. 
| Development team
|
* Carlos Menéndez González (UO288056@uniovi.es)
* Didier Yamil Reyes Castro (UO287866@uniovi.es)
* Iyán Robles Suárez (UO288780@uniovi.es)
* Raúl Mera Soto (UO287827@uniovi.es)
* Mateo Rico Iglesias (UO277172@uniovi.es)
* Anna Kutova (UO305098@uniovi.es)
* Diego Murias Suárez (UO290009@uniovi.es)
| A good documented and clean code that fulfills the expected requirements. Also, a well implemented System that makes it easier for maintenance and extension.
|===
