ifndef::imagesdir[:imagesdir: ../images]

[[section-solution-strategy]]
== Solution Strategy


[role="arc42help"]
****
.Contents
A short summary and explanation of the fundamental decisions and solution strategies, that shape system architecture. It includes

* technology decisions
* decisions about the top-level decomposition of the system, e.g. usage of an architectural pattern or design pattern
* decisions on how to achieve key quality goals
* relevant organizational decisions, e.g. selecting a development process or delegating certain tasks to third parties.

.Motivation
These decisions form the cornerstones for your architecture. They are the foundation for many other detailed decisions or implementation rules.

.Form
Keep the explanations of such key decisions short.

Motivate what was decided and why it was decided that way,
based upon problem statement, quality goals and key constraints.
Refer to details in the following sections.


.Further Information

See https://docs.arc42.org/section-4/[Solution Strategy] in the arc42 documentation.

****

=== Technologies

- *React* : React will simplify the task build reusable and modular UI elements for our application thanks to its component-based structure. It also allows us to use JSX, which is a syntax extension for JavaScript that allows us to write HTML elements inside our JavaScript code. This will make our code more readable and easier to debug.
- *Express* : Web application framework for Node.js which will simplify development on the server side. There is also available a wide range of third-party middlewares that we could include on our application.
- *TypeScript* : Since we will be using JavaScript and are more familiar with statically typed languages we will use TypeScript for the services of our application. This will also reduce the likelihood of some unexpected errors at runtime.
- *MongoDB* : We chose MongoDB since we consider we could take advantage of it's flexible schema. Its native support for JSON and its simple query language also influenced our decision. We also consider this a valauable oportunity to learn and work with a document database.
- *Docker*: To deploy our project, Docker was chosen due to its handy portability and its perfect integration with microservices applications. 


=== Decomposition of the System 

==== Arquitectural patterns
- *Microservices*: 
As the main architecture for the whole project. The system is divided into several modules representing
a functional requirement like question generation. Each of these modules will be independent from
each other and have its own database.

- *RESTful APIs*:
The main architecture for our Services to function as an API. Clients can communicate through
over HTTPS using standard methods, such as GET to consult information like history data or
generate questions using Wikidata. All these services are "masked" through a middleware so
clients do not have to access different endpoints.

- *Gateway*
A middleware that acts as an API-frontend for clients to access various services within our system.
This component can be also seen as a "Controller" since it receives petitions from outside, calls the
corresponding service that answers that petition and returns its value.

=== Decisions to Achieve Quality Goals 

|===
| Quality goal | Scenario | Approach 

| Security 
| Ensuring secure methods of authentication, such as login credentials (username and password), to protect user accounts from unauthorized access.  
| Implementation of secure authentication mechanisms with mechanisms such as JWT, encryption for data in transit using HTTPS, and security enforcement automation with tools such as SonarCloud.

| Performance 
| Web-app should work smoothly and respond quickly.  
| Implementing caching mechanisms for Question generation.
  Optimizing database queries through indexing and query optimization techniques.

| Usability 
| The application aims for user-friendly accessibility with an intuitive design. 
| Different web tools can be used to test accesibility and responsive design such as 
https://chromewebstore.google.com/detail/lighthouse/blipmdconlkpinefehnmjammfjpmpbjk?hl=es&pli=1[Google LightHouse], https://webaim.org/resources/contrastchecker/[Contrast Checker] or https://wave.webaim.org/[Wave].
|===


=== Organization and management
The team will follow the SCRUM methodology to focus on continuous delivering of products with value to 
the stakeholders as well as improving the quality of the whole project in each iteration. 

Each week the team will have a meeting to discuss the work performed
through the week, the tasks not done and all the decisions taken for next weeks, which will 
be recorded on the Wiki of the GitHub repository. All the work performed and its progress is going to be tracked by means of the Kanban and the issues.
Any unforeseen issue that may arise during development will be discussed in the issue itself or via our WhatsApp group if of low relevance or importance.

In the end, SCRUM promotes the continuous collaboration of the team to ship quality products
that stakeholders can really make value of, which is one of the objectives from the team.