ifndef::imagesdir[:imagesdir: ../images]

[[section-building-block-view]]


== Building Block View
 
=== Scope and Context

[mermaid]
....
flowchart LR
    u("fa:fa-users 
    Users")
    wiq("fa:fa-question Saber y Ganar 
    Application")
    wd("fa:fa-book
    WikiData")
    u--"interact"-->wiq
    wiq--"request"-->wd
    wd--"response"-->wiq
....

Motivation::

The diagram above shows the high-level abstraction of the functionality
of the system. As it can be seen, there are two main 
components: Users and Application; and one External service: Wikidata.
The general workflow consists on a series of interactions done by the users through
the different components exposed by the Application. During the game, the application
will require the help of the external service to generate the different questions
and answers that the user will have to choose.

Contained Building Blocks::

[cols="1,2" options="header"]
|===
| **Building block** | **Description** 
| Saber y Ganar Application | The core block that manages the game itself and the visuals of it.
| WikiData | API that offers the Application an easy-to-use interface to perform queries for the question and answer generation.
|===

=== Level 1: 

[mermaid]
....
flowchart TD
    u("fa:fa-users"
    User) --"interact"--> Frontend

    subgraph app [Saber y Ganar]
        Frontend("fa:fa-home"
        Frontend)
        Gateway(
        Gateway)
        Microservices(
        Microservices)
       
    end
    
    Frontend --> Gateway
    Gateway --> Microservices
....

Motivation::

In this level of decomposition, we illustrate the primary services of our system. The Frontend service serves as the entry point for user interactions, directing them to the Gateway. The Gateway then routes these interactions to the appropriate microservices for processing. This diagram emphasizes the flow of interactions through the system's components.


Contained Building Blocks::

|===
| **Building block** | **Description** 
| Frontend | Service responsible for collecting user interactions and routing them to the Gateway.
| Gateway | Middleware component that routes user interactions to the appropriate microservices.
| Microservices | Collection of smaller services responsible for handling various functionalities of the application.
|===

=== Level 2:

[mermaid]
....
flowchart TD
    u("fa:fa-users" User) --"interact"--> WebApp

    subgraph app [Saber y Ganar]
        subgraph front [Frontend]
            WebApp("fa:fa-home" WebApp)
        end
        WebApp --"send request"--> Gateway
        subgraph back [Backend]
            Gateway
            AuthService("fa:fa-user-cog" AuthService)
            UserService("fa:fa-user-cog" UserService)
            QuestionService("fa:fa-gamepad" QuestionService)
            UserDatabase("fa:fa-database" UserDatabase)
        end
    end

    Wikidata("fa:fa-book" Wikidata API)
    
    AuthService --> UserDatabase
    UserService --> UserDatabase
    Gateway --> AuthService
    AuthService --> Gateway
    Gateway --> UserService
    UserService --> Gateway
    Gateway --> QuestionService
    QuestionService --> Gateway
    QuestionService --> Wikidata
    Wikidata --> QuestionService
    style Wikidata fill:#fff,stroke:#000,stroke-width:2px,rx:20px,ry:20px
    classDef subgraphstyle margin-left:3cm
    class back subgraphstyle
    class front subgraphstyle
....

Motivation::

This diagram shows a more detailed view of the functionality
of the system, showing the gateway and the different microservices.
The user interacts with the WebApp, which sends requests to the Gateway. 
The Gateway then communicates with the different microservices to perform various operations. 
The QuestionService also interacts with the Wikidata API to generate questions and answers. 
The results are then sent back to the user through the same path. 
This architecture allows for a separation of concerns, where each component has a specific role and responsibility.

Contained Building Blocks::

[cols="1,2" options="header"]
|===
| **Building block** | **Description** 
| WebApp | Component that Users interact with. It represents all the visuals and interactivity of the Web Application.
| Gateway | MiddleWare that connects the WebApplication with the different MicroServices of the Application.
| AuthService | It manages all the actions referred to the authentication of a user into the system. Also, the different registration of them.
| UserService | It manages all the acions referred to the users such as retrieval of game history.
| QuestionService | Handles the Question and Answers generation. This action is complemented with the use of Wikidata API.
|===