ifndef::imagesdir[:imagesdir: ../images]

[[section-runtime-view]]
== Runtime View


[role="arc42help"]
****
.Contents
The runtime view describes concrete behavior and interactions of the system’s building blocks in form of scenarios from the following areas:

* important use cases or features: how do building blocks execute them?
* interactions at critical external interfaces: how do building blocks cooperate with users and neighboring systems?
* operation and administration: launch, start-up, stop
* error and exception scenarios

Remark: The main criterion for the choice of possible scenarios (sequences, workflows) is their *architectural relevance*. It is *not* important to describe a large number of scenarios. You should rather document a representative selection.

.Motivation
You should understand how (instances of) building blocks of your system perform their job and communicate at runtime.
You will mainly capture scenarios in your documentation to communicate your architecture to stakeholders that are less willing or able to read and understand the static models (building block view, deployment view).

.Form
There are many notations for describing scenarios, e.g.

* numbered list of steps (in natural language)
* activity diagrams or flow charts
* sequence diagrams
* BPMN or EPCs (event process chains)
* state machines
* ...


.Further Information

See https://docs.arc42.org/section-6/[Runtime View] in the arc42 documentation.

****

=== <Runtime Scenario 1>

**Diagram**

image::loginSequence.svg[Login]

**Mermaid code**
[mermaid]
....
sequenceDiagram
    Title: User Login
    User->Frontend: Navigates to login page
    Frontend->Backend: Requests login page
    Backend-->Frontend: Sends login page
    Frontend-->User: Displays login page
    User->Frontend: Enters details (username, password)
    Frontend->Backend: Sends user details
    Backend->Database: Verifies user credentials
    Database-->Backend: Responds with verification status
    alt Credentials are incorrect
        Backend-->Frontend: Sends error message "Incorrect credentials"
        Frontend-->User: Displays error message "Incorrect credentials"
    else Credentials are correct
        Backend-->Frontend: Sends success message "Login successful"
        Frontend-->User: Displays success message "Login successful"
    end
....

**Link to the editor**

https://www.mermaidchart.com/app/projects/c3b49db4-8a97-41da-a57e-a5c16b123f08/diagrams/d83267ef-0337-4c1d-b450-39dfb61cc6b4/version/v0.1/edit

* _<insert runtime diagram or textual description of the scenario>_
* _<insert description of the notable aspects of the interactions between the
building block instances depicted in this diagram.>_

It is possible to use a sequence diagram:

=== Question Generation
When a user starts a game, all the questions for the game are created. The process is represented on the following diagram.

[mermaid]
....
 sequenceDiagram
    actor U as User
    participant FE as Frontend 
    participant BE as Backend 
    participant QGS as Question Generation Service 
    participant WQS as Wikidata Query Service 
    participant DB as Database 

    U->>FE: Starts a Game
    FE->>BE: Requests Questions
    BE->>QGS: Generate Questions

    loop for each question
        QGS->>DB: Request Question Template
        DB->>QGS: Return Question Template
        QGS->>WQS: Request Data
        WQS->>QGS: Return Data
        QGS->>QGS: Fill Template
        QGS->>WQS: Request Answer + Distractors
        WQS->>QGS: Return Answer + Distractors
        QGS->>QGS: Create Question
    end 
    QGS->>BE: Return Questions
    BE->>FE: Return Questions
    FE->>U: Display Questions
....

=== ...

=== <Runtime Scenario n>
