ifndef::imagesdir[:imagesdir: ../images]

[[section-concepts]]
== Cross-cutting Concepts

=== Domain model

=== UX

=== Security

=== Architecture and design patterns

==== MicroServices


=== "Under-the-hood" concepts

==== Persistency

As stated in point 4.1, the chosen database for the project is MongoDB 
which offers us a document-oriented schema. This type of database fits
perfectly with our services since the mainly work with JSON-formatted data. 

===== ER model

[mermaid]
....
erDiagram
    
    QUESTION_TEMPLATE ||--|| QUESTION_TYPE:has
    USER ||--|| USER_HISTORY:has

    USER{
        Long id
        String username
        String password
    }

    USER_HISTORY{
        int passedQuestions
        int wrongQuestions
        int gamesPlayed
        String timesPlayed
        int points
    }
    
    QUESTION_TEMPLATE{
        Long id
        String template
    }
    
    QUESTION_TYPE{
        String name
        String query
    }
....

|===
| Document | Description 
| USER 
| Holds all the data relationed to a user registered into our game. It
has a relation with *ONE USER_HISTORY* document which represents the records/statistics 
of them as it is a system requisite.  
| QUESTION_TEMPLATE
| Holds the template needed to query the WikiData API for the Question generation. It
has a reation with *ONE QUESTION_TYPE* document which represents a category for that
question (e.g. Capitals) together with its SPARQL query.
|===

===== Connection to MongoDB

To make it easier the connection from Services (using ExpressJS) to MongoDB, the
usage of *Mongoose* has been chosen. This is a JS library that help us to create these 
connections. 

flowchart LR
    subgraph back [Backend]
        subgraph micro [MicroServices]
            as("fa:fa-user-cog" AuthService)
            us("fa:fa-user-cog" UserService)
            qs("fa:fa-gamepad" QuestionService)
        end
        m("fa:fa-book
        Mongoose Schema")
        subgraph mongo [MongoDB]
            ud("fa:fa-database" UserDatabase)
            td("fa:fa-database" TemplateDatabase)
        end
    end
    as <--> m <--> ud
    us <--> m
    qs <--> m <-->td

==== Session handling

==== Business Rules

=== Development concepts

==== Testing

==== Deployment

< Could add more in the future...Refer to https://docs.arc42.org/section-8/ >

=== 