ifndef::imagesdir[:imagesdir: ../images]

[[section-design-decisions]]
== Architecture Decisions


[role="arc42help"]
****
.Contents
Important, expensive, large scale or risky architecture decisions including rationales.
With "decisions" we mean selecting one alternative based on given criteria.

Please use your judgement to decide whether an architectural decision should be documented
here in this central section or whether you better document it locally
(e.g. within the white box template of one building block).

Avoid redundancy. 
Refer to section 4, where you already captured the most important decisions of your architecture.

.Motivation
Stakeholders of your system should be able to comprehend and retrace your decisions.

.Form
Various options:

* ADR (https://cognitect.com/blog/2011/11/15/documenting-architecture-decisions[Documenting Architecture Decisions]) for every important decision
* List or table, ordered by importance and consequences or:
* more detailed in form of separate sections per decision

.Further Information

See https://docs.arc42.org/section-9/[Architecture Decisions] in the arc42 documentation.
There you will find links and examples about ADR.

****

=== Using microservices and gateway
.Alternatives considered
One possible alternative to microservices could be monolithic architecture for simplicity but potential scalability
and maintenance challenges. We didn't choose this approach because we think that the code would become unmaintainable
quite fast. Also, the alternative to the gateway would be to have direct connections between the client and the services.

.Goals of this decision
We have chosen the microservice architecture mainly for it's better maintainability since the different microservices
are isolated. They also have more flexibility and scalability. The gateway allows us to handle errors more easily and
it also allows clients to use the api as a whole.

=== Creating a RESTful API
.Alternatives considered
An alternative could be SOAP (Simple Object Access Protocol), which offers features like built-in security and reliability
but tends to be more heavyweight and less scalable compared to REST.

.Goals of this decision
Our main reason for choosing REST is for simplicity, since they are easier to develop.
Using RESTful principles promotes a uniform interface, making it easier to understand and consume the API.

=== Using NoSQL
.Alternatives considered
An alternative could be traditional SQL databases like MySQL or PostgreSQL, which offer strong ACID compliance and are
well-suited for structured data with complex relationships. We didn't choose SQL because we are not dealing with complex
relationships between entities.

.Goals of this decision
We chose MongoDB mainly for it's great flexibility, since it allows handling unstructured data. That also makes it simpler
to use.