ifndef::imagesdir[:imagesdir: ../images]

[[section-quality-scenarios]]
== Quality Requirements


[role="arc42help"]
****

.Content
This section contains all quality requirements as quality tree with scenarios. The most important ones have already been described in section 1.2. (quality goals)

Here you can also capture quality requirements with lesser priority,
which will not create high risks when they are not fully achieved.

.Motivation
Since quality requirements will have a lot of influence on architectural
decisions you should know for every stakeholder what is really important to them,
concrete and measurable.


.Further Information

See https://docs.arc42.org/section-10/[Quality Requirements] in the arc42 documentation.

****

=== Quality Tree

[role="arc42help"]
****
.Content
The quality tree (as defined in ATAM – Architecture Tradeoff Analysis Method) with quality/evaluation scenarios as leafs.

.Motivation
The tree structure with priorities provides an overview for a sometimes large number of quality requirements.

.Form
The quality tree is a high-level overview of the quality goals and requirements:

* tree-like refinement of the term "quality". Use "quality" or "usefulness" as a root
* a mind map with quality categories as main branches

In any case the tree should include links to the scenarios of the following section.


****

[mermaid]
....
graph TD
    A[Quality] --> B[Usability]
    A --> C[Availability]
    A --> D[Accessibility]
    A --> E[Security]
    A --> F[Performance]
    A --> H[Privacy]
    A --> I[Testability]
    A --> J[Adaptability]
....

=== Quality Scenarios

[role="arc42help"]
****
.Contents
Concretization of (sometimes vague or implicit) quality requirements using (quality) scenarios.

These scenarios describe what should happen when a stimulus arrives at the system.

For architects, two kinds of scenarios are important:

* Usage scenarios (also called application scenarios or use case scenarios) describe the system’s runtime reaction to a certain stimulus. This also includes scenarios that describe the system’s efficiency or performance. Example: The system reacts to a user’s request within one second.
* Change scenarios describe a modification of the system or of its immediate environment. Example: Additional functionality is implemented or requirements for a quality attribute change.

.Motivation
Scenarios make quality requirements concrete and allow to
more easily measure or decide whether they are fulfilled.

Especially when you want to assess your architecture using methods like
ATAM you need to describe your quality goals (from section 1.2)
more precisely down to a level of scenarios that can be discussed and evaluated.

.Form
Tabular or free form text.
****

==== Usage Scenarios

[cols="1,3,1",options="header"]
|===
| Quality requirement | Scenario | Priority

| Usability
| When new users access the application the design should be intuitive enough, allowing them to navigate through the system and play the game easily.
The application should meet usability standards.
| High

| Performance
| When a user interacts with the system it should react within one second to ensure a smooth and responsive user experience.
| High

| Privacy
| If a user provides personal information during the registration, the application should securely handle and store user-provided personal information.
Encryption should be applied for data storage.
| High

| Security
| If a malicious user attempts unauthorized access to the application, the application should implement robust authentication mechanisms,
including secure password storage to prevent unauthorized access.
| High

| Adaptability
| If a user accesses the application from a different device than a PC, the application should be able to adapt to the different screen size, providing a satisfactory user experience.
| Medium

| Accessibility
| In case a user with a visual impairment interacts with the web application, it should follow HTML standards to ensure accessibility.
All interactive elements must be navigable using screen readers, text alternatives should be provided for non-text content.
Additionally, the application's color contrast should be enough for people with color blindness.
| Medium

| Availability
| Users should be able to access the application at any time, with an availability of about 95%.
| Medium

|===

==== Change Scenarios

[cols="1,3,1",options="header"]
|===
| Quality requirement | Scenario | Priority

| Maintainability
| When new functionalities need to be added to the application, they should be easy to integrate.
The application should have a good architecture and design that makes the code more modular, allowing easier maintenance.
The documentation should also be clear for potential new team members.
| High

| Usability
| New usability improvements should be implemented based on user feedback and usability testing.
| High

| Security
| Different components of the application should be updated frequently to protect against evolving threats and vulnerabilities.
| High

| Testability
| When new features are added to the application, new tests should be performed and they should be easy to add.
The application must be designed to facilitate testing across new scenarios.
| High

|===