@startuml BusinessContext

actor User
component  WIQ
component QuestionService
component Wikidata

User ..> WIQ : interacts
WIQ --> QuestionService :  Requests questions
QuestionService --> WIQ : Generates questions
QuestionService --> Wikidata : Requests data

@enduml
