@startuml BusinessContext

actor User
component  WebApp
component QuestionService
component Wikidata

User .right.> WebApp : interacts
WebApp -right-> QuestionService :  Requests questions
QuestionService -left-> WebApp : Generates questions
QuestionService -right-> Wikidata : Requests data

@enduml
