@startuml Technical Context
actor User
actor API_Consumer

node Application {
    component  WebApp
    component  Services
    component Database
}

cloud  Wikidata

User .right.> WebApp : http
API_Consumer .up.>Services : http
WebApp <-> Services : http
Services <-> Database : mongoose
Services <--> Wikidata : http(SPARQL)
@enduml