name: Build and Deploy of Documentation
on:
    push:
      branches:
        - master
    release:
        types: [published]
permissions:
    contents: write
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Install Ruby
              uses: ruby/setup-ruby@v1
              with:
                ruby-version: 3.0
            - name: Install Node
              uses: actions/setup-node@v1
              with:
                node-version: 20
            - name: Install Asciidoctor
              run: gem install asciidoctor asciidoctor-diagram
            - name: Installing dependencies
              run: cd docs/ && npm install
            - name: Building docs
              run: cd docs/ && npm run build
            - name: Deploying docs
              uses: JamesIves/github-pages-deploy-action@v4
              with:
                folder: docs/build

    
